// The module's own API, typed from the module itself.
//
// Every view type here is generated by ts-rs from `src/api.rs`, so the
// contract cannot drift: change a Rust struct and this stops compiling.

import type { AttributeView } from './generated/AttributeView'
import type { EntityView } from './generated/EntityView'
import type { GraphView } from './generated/GraphView'
import type { TreeNodeView } from './generated/TreeNodeView'

export type { AttributeView, EntityView, GraphView, TreeNodeView }
export type { GraphNodeView } from './generated/GraphNodeView'
export type { GraphEdgeView } from './generated/GraphEdgeView'
export type { LabelView } from './generated/LabelView'
export type { LinkView } from './generated/LinkView'

async function json<T>(path: string, init?: RequestInit): Promise<T> {
  const r = await fetch(path, {
    ...init,
    headers: init?.body ? { 'content-type': 'application/json' } : undefined,
  })
  if (!r.ok) throw new Error((await r.text()) || r.statusText)
  return (await r.json()) as T
}

export const fetchPing = () =>
  json<{ module: string; version: string; core_url: string | null }>('/api/ping')

/// EVERY entity, for the pickers. A label is an entity carrying the
/// label `label`, and a link target is any entity at all — so what a
/// picker must offer is the whole set, never a subset the module chose.
export const fetchAllEntities = (archived = false) =>
  json<TreeNodeView[]>(`/api/entities/all?archived=${archived}`)

export const searchEntities = (q: string, archived = false) =>
  json<TreeNodeView[]>(
    `/api/entities/search?q=${encodeURIComponent(q)}&archived=${archived}`,
  )

export const fetchRoots = (archived = false) =>
  json<TreeNodeView[]>(`/api/entities?archived=${archived}`)

export const fetchChildren = (frag: string, label?: string) =>
  json<TreeNodeView[]>(
    `/api/entities/${frag}/children${label ? `?label=${label}` : ''}`,
  )

export const fetchEntity = (frag: string) => json<EntityView>(`/api/entities/${frag}`)

export const fetchGraph = (frag: string, depth: number, label?: string) =>
  json<GraphView>(
    `/api/entities/${frag}/graph?depth=${depth}${label ? `&label=${label}` : ''}`,
  )

export const createEntity = (name: string) =>
  json<{ uuid: string }>('/api/entities', {
    method: 'POST',
    body: JSON.stringify({ name }),
  })

export const putAttribute = (
  frag: string,
  req: {
    uid?: string | null
    name: string
    datatype: string
    content?: unknown
    labels?: string[]
    options?: unknown
  },
) =>
  json<{ uid: string }>(`/api/entities/${frag}/attributes`, {
    method: 'POST',
    body: JSON.stringify(req),
  })

export const linkEntities = (frag: string, to: string, name: string, labels: string[] = []) =>
  json<{ uid: string }>(`/api/entities/${frag}/link`, {
    method: 'POST',
    body: JSON.stringify({ to, name, labels }),
  })

/// Take a field off the screen. The record keeps every version (§10).
export const retireAttribute = (frag: string, uid: string) =>
  json<{ changed: boolean }>(`/api/entities/${frag}/attributes/${uid}/retire`, { method: 'POST' })

/// Cut a link from either end.
export const unlinkEntities = (frag: string, uid: string) =>
  json<{ changed: boolean }>(`/api/entities/${frag}/unlink`, {
    method: 'POST',
    body: JSON.stringify({ uid }),
  })

export const setArchived = (frag: string, archived: boolean) =>
  json<{ changed: boolean }>(`/api/entities/${frag}/archive`, {
    method: 'POST',
    body: JSON.stringify({ archived }),
  })

/// The five datatypes, and the ONE control each of them gets. There is
/// no widget layer: an email is `text` with a label that says `email`.
export const DATATYPES = ['text', 'number', 'boolean', 'datetime', 'json'] as const
export type Datatype = (typeof DATATYPES)[number]

/// THE PALETTE. Everything on an entity's screen is one of these, added
/// by hand (operator, 2026-09-03: "one field is required, name; the rest
/// is added" · "connection is also a field you add" · "[labels are] just a
/// field that you add"). Five datatypes, plus the entity's own labels,
/// plus a link to another entity.
///
/// SIZES ARE COMPACT ON PURPOSE, in grid units of a 12-column row: prose
/// half a row and five rows tall, a number a quarter row, a yes/no a
/// sixth. Nothing spans the full width unless someone drags it there —
/// full-width cards stacked one per row were the "long ugly fields".
export type Kind = Datatype | 'labels' | 'link'
export const PALETTE: { kind: Kind; title: string; hint: string; w: number; h: number }[] = [
  { kind: 'text', title: 'Text', hint: 'prose, with formatting', w: 6, h: 5 },
  { kind: 'number', title: 'Number', hint: 'a quantity', w: 3, h: 3 },
  { kind: 'boolean', title: 'Yes / no', hint: 'a switch', w: 2, h: 3 },
  { kind: 'datetime', title: 'Date', hint: 'an instant', w: 3, h: 3 },
  { kind: 'json', title: 'JSON', hint: 'structure the database can query', w: 6, h: 5 },
  { kind: 'labels', title: 'Labels', hint: 'what this entity IS', w: 6, h: 3 },
  { kind: 'link', title: 'Link', hint: 'to another entity — links join entities only', w: 6, h: 3 },
]
export const SIZE: Record<Kind, { w: number; h: number }> = Object.fromEntries(
  PALETTE.map((p) => [p.kind, { w: p.w, h: p.h }]),
) as Record<Kind, { w: number; h: number }>

/// The name is one line, drawn wide enough to read: two thirds of a row.
export const NAME_SIZE = { w: 8, h: 3 }

export function isDatatype(s: string): s is Datatype {
  return (DATATYPES as readonly string[]).includes(s)
}

/// Attributes the module keeps for itself. They are ordinary rows — the
/// store has no notion of a reserved name — but they are machinery, not
/// something the operator typed, so the field list leaves them out.
///
/// `archived` especially: rendering it as a checkbox let someone flip it
/// straight past the Archive button, leaving the header saying one thing
/// and the record another.
export const SCREEN = 'screen'
export const ARCHIVED = 'archived'
export const NAME = 'name'

/// The name of the content-less attribute that says what an entity IS.
export const IS = 'is' // skill-allow: §9-const — the module's own vocabulary, not a tunable

/// THE ONE WORD THE INTERFACE KNOWS. A label is an entity carrying the
/// label `label` (operator, 2026-09-03: "an entity that has label
/// attached to it is a label"). This is how the pickers tell vocabulary
/// from things and what *New label* attaches. The Rust side knows
/// nothing of it — it stores and describes — so the word lives here,
/// beside the other names the interface keeps for itself.
export const LABEL = 'label' // skill-allow: §9-const — the module's own vocabulary, not a tunable

export const isLabel = (n: { labels: { name: string }[] }) => n.labels.some((l) => l.name === LABEL)

/// `is` is machinery too: the row that says what a thing IS is drawn as
/// chips in the header, never as a field — and once its last label is
/// removed it would otherwise surface as an empty text field called `is`.
export const MACHINERY: readonly string[] = [SCREEN, ARCHIVED, IS]

/// The declaration row: the newest content-less `is` attribute, if any.
///
/// ONE ROW, AMENDED. "Label it" used to append a fresh `is` row on every
/// click, each repeating the labels before it — two clicks, two rows — and
/// nothing could take a label off again. A declaration is one chain like
/// any other attribute: add to it, remove from it, and its history is the
/// history of what the thing has been.
export const declarationOf = (attrs: AttributeView[]): AttributeView | undefined => {
  const rows = attrs.filter((a) => a.name === IS && a.content === null)
  return rows[rows.length - 1]
}

/// Set what an entity IS to exactly `labels`, amending its declaration
/// row or starting one.
export const declareLabels = (frag: string, attrs: AttributeView[], labels: string[]) =>
  putAttribute(frag, {
    uid: declarationOf(attrs)?.uid ?? null,
    name: IS,
    datatype: 'text',
    content: null,
    labels,
  })
