// The module's own API, typed from the module itself.
//
// Every view type here is generated by ts-rs from `src/api.rs`, so the
// contract cannot drift: change a Rust struct and this stops compiling.

import type { AttributeView } from './generated/AttributeView'
import type { EntityView } from './generated/EntityView'
import type { GraphView } from './generated/GraphView'
import type { TreeNodeView } from './generated/TreeNodeView'

export type { AttributeView, EntityView, GraphView, TreeNodeView }
export type { GraphNodeView } from './generated/GraphNodeView'
export type { GraphEdgeView } from './generated/GraphEdgeView'
export type { LabelView } from './generated/LabelView'
export type { LinkView } from './generated/LinkView'

async function json<T>(path: string, init?: RequestInit): Promise<T> {
  const r = await fetch(path, {
    ...init,
    headers: init?.body ? { 'content-type': 'application/json' } : undefined,
  })
  if (!r.ok) throw new Error((await r.text()) || r.statusText)
  return (await r.json()) as T
}

export const fetchPing = () => json<{ module: string; version: string }>('/api/ping')

export const fetchRoots = (archived = false) =>
  json<TreeNodeView[]>(`/api/entities?archived=${archived}`)

export const fetchChildren = (frag: string, label?: string) =>
  json<TreeNodeView[]>(
    `/api/entities/${frag}/children${label ? `?label=${label}` : ''}`,
  )

export const fetchEntity = (frag: string) => json<EntityView>(`/api/entities/${frag}`)

export const fetchGraph = (frag: string, depth: number, label?: string) =>
  json<GraphView>(
    `/api/entities/${frag}/graph?depth=${depth}${label ? `&label=${label}` : ''}`,
  )

export const createEntity = (name: string) =>
  json<{ uuid: string }>('/api/entities', {
    method: 'POST',
    body: JSON.stringify({ name }),
  })

export const putAttribute = (
  frag: string,
  req: {
    uid?: string | null
    name: string
    datatype: string
    content?: unknown
    labels?: string[]
    options?: unknown
  },
) =>
  json<{ uid: string }>(`/api/entities/${frag}/attributes`, {
    method: 'POST',
    body: JSON.stringify(req),
  })

export const linkEntities = (frag: string, to: string, name: string, labels: string[] = []) =>
  json<{ uid: string }>(`/api/entities/${frag}/link`, {
    method: 'POST',
    body: JSON.stringify({ to, name, labels }),
  })

export const setArchived = (frag: string, archived: boolean) =>
  json<{ changed: boolean }>(`/api/entities/${frag}/archive`, {
    method: 'POST',
    body: JSON.stringify({ archived }),
  })

/// The five datatypes, and the ONE control each of them gets. There is
/// no widget layer: an email is `text` with a label that says `email`.
export const DATATYPES = ['text', 'number', 'boolean', 'datetime', 'json'] as const
export type Datatype = (typeof DATATYPES)[number]

/// How tall a field wants to be, in grid rows. A date needs a box; prose
/// needs room. This is the default a new field lands with — the designer
/// overrides it and the override is saved.
export const NATURAL_HEIGHT: Record<Datatype, number> = {
  text: 6,
  json: 6,
  number: 2,
  boolean: 2,
  datetime: 2,
}

export const NATURAL_WIDTH: Record<Datatype, number> = {
  text: 12,
  json: 12,
  number: 3,
  boolean: 3,
  datetime: 4,
}

export function isDatatype(s: string): s is Datatype {
  return (DATATYPES as readonly string[]).includes(s)
}

/// The attribute an entity's own screen layout is saved in.
export const SCREEN = 'screen'
