use chrono::{DateTime, Utc};
use surrealdb::engine::any::{connect, Any};
use surrealdb::opt::auth::Database;
use surrealdb::types::{RecordId, SurrealValue};
use surrealdb::Surreal;
use uuid::Uuid;

use crate::error::Result;

/// Service-account username — the only credential the model is permitted
/// to use after schema deploy. Locked by SKILL.md §13.
const SERVICE_USERNAME: &str = "superx";

/// Env var the operator sets to provision the service-account password.
const SERVICE_PASSWORD_ENV: &str = "SUPERX_SERVICE_PASSWORD";

/// v0.1 dev default published in SKILL.md §13 + SUPERX_SCHEMA.md
/// "Database users + access". Operator overrides via the env var above.
/// Documented in the skill so the literal here is the skill, not magic.
const SERVICE_PASSWORD_DEV_DEFAULT: &str = "superx-v01-dev-x9KmP2nQ7tR3vW8y";

/// The substrate kernel — the model's only access path to SurrealDB.
///
/// A `Kernel` owns one [`Surreal<Any>`] connection that is signed in as
/// the `superx` EDITOR service account against an operator-provisioned
/// substrate (where `scripts/deploy-schema.sh` has already applied
/// the locked schema). Every typed verb on this struct issues only
/// `CREATE` or `SELECT` SQL — there is no `UPDATE`-emitting and no
/// `DELETE`-emitting method by design.
pub struct Kernel {
    db: Surreal<Any>,
}

impl Kernel {
    /// Connect to an operator-provisioned SurrealDB and sign in as
    /// the `superx` service account.
    ///
    /// `endpoint` is a SurrealDB connection URL — `ws://host:port`,
    /// `wss://host:port`, `http://host:port`, `https://host:port`, or
    /// (in tests) `mem://`. `namespace` and `database` select the
    /// SuperX deployment within the engine.
    ///
    /// The service-account password is read from the
    /// `SUPERX_SERVICE_PASSWORD` env var; if absent it falls back to
    /// the v0.1 dev default documented in SKILL.md §13.
    ///
    /// # Errors
    ///
    /// Returns [`crate::KernelError::Db`] if the engine refuses the
    /// connection, the namespace/database selection, or the signin —
    /// e.g. when the schema has not been deployed yet or the password
    /// does not match the one bound at schema-deploy time.
    pub async fn connect_service(
        endpoint: &str,
        namespace: &str,
        database: &str,
    ) -> Result<Self> {
        let password = std::env::var(SERVICE_PASSWORD_ENV)
            .unwrap_or_else(|_| SERVICE_PASSWORD_DEV_DEFAULT.to_string());

        let db = connect(endpoint).await?;
        db.use_ns(namespace).use_db(database).await?;
        db.signin(Database {
            namespace: namespace.to_string(),
            database: database.to_string(),
            username: SERVICE_USERNAME.to_string(),
            password,
        })
        .await?;

        Ok(Self { db })
    }

    /// Wrap an already-authenticated [`Surreal<Any>`] connection.
    ///
    /// Intended for integration tests that hand-construct the
    /// substrate (`mem://` engine, schema applied, signed in) and want
    /// to exercise the kernel verbs against it. Production code paths
    /// go through [`Kernel::connect_service`].
    #[must_use]
    pub fn from_db(db: Surreal<Any>) -> Self {
        Self { db }
    }

    /// Underlying SurrealDB handle.
    ///
    /// Subsequent feature PRs will replace direct handle access with
    /// typed verbs; for now it is exposed so the next PR's verbs can
    /// build on top of the same connection without re-signin.
    #[must_use]
    pub fn db(&self) -> &Surreal<Any> {
        &self.db
    }

    /// Append one row to `telemetry_stream` with an explicit UUIDv7 id.
    ///
    /// Per [SKILL.md §8] every kernel mutation emits a typed
    /// `telemetry_stream` event; this is the verb every other kernel
    /// verb will call once the next PR adds them. The id is set by
    /// the kernel (UUIDv7, §11), never auto-generated by the engine.
    ///
    /// `tenant` must reference a `node_substrate` entity (engine
    /// asserts this); `run` may reference a `node_run` entity or
    /// be `None` for events with no run context (e.g. bootstrap).
    ///
    /// # Errors
    ///
    /// Surfaces engine refusals verbatim via [`crate::KernelError::Db`].
    /// Per [SKILL.md §13], the caller's response to a refusal is to
    /// fix the kernel verb's call shape, never to authenticate as root.
    pub async fn log_telemetry(
        &self,
        lifecycle_event: &str,
        payload: surrealdb::types::Value,
        tenant: RecordId,
        run: Option<RecordId>,
    ) -> Result<RecordId> {
        let id = RecordId::new(
            "telemetry_stream",
            surrealdb::types::Uuid::from(Uuid::now_v7()),
        );
        let row = TelemetryRow {
            lifecycle_event: lifecycle_event.to_string(),
            payload,
            run,
            tenant,
            valid_from: Utc::now(),
        };

        let _: Option<TelemetryRow> = self.db.create(id.clone()).content(row).await?;
        Ok(id)
    }
}

#[derive(Debug, SurrealValue)]
struct TelemetryRow {
    lifecycle_event: String,
    payload: surrealdb::types::Value,
    run: Option<RecordId>,
    tenant: RecordId,
    valid_from: DateTime<Utc>,
}
