//! The Kernel struct + substrate verbs.
//!
//! `Kernel` owns one [`Surreal<Any>`] connection authenticated as the
//! `superx_kernel` service account (skill §13). All substrate access
//! by any layer above (modules, adapters, the CLI) goes through these
//! verbs. There is NO `update_*`, no `delete_*`, no `upsert_*`, no
//! `connect_root` — the append-only invariant is enforced by what the
//! API does NOT contain (skill §10).
//!
//! Every row id is set explicitly by the kernel as a UUIDv7 — never
//! auto-generated by the engine (SUPERX_SCHEMA.md §1).

use chrono::{DateTime, Utc};
use surrealdb::engine::any::{connect, Any};
use surrealdb::opt::auth::Database;
use surrealdb::types::{RecordId, SurrealValue, Value};
use surrealdb::Surreal;
use uuid::Uuid;

use crate::error::{KernelError, Result};

/// Kernel service-account username — the kernel's only credential
/// after schema deploy. Fixed by SUPERX_SCHEMA.md §2.
const SERVICE_USERNAME: &str = "superx_kernel";

/// Env var the operator sets to provision the kernel service-account
/// password — the same var `scripts/deploy-schema.sh` requires at
/// schema-apply time (SUPERX_SCHEMA.md §2). There is no fallback
/// default: an unset var is a configuration error, never a silently
/// weaker credential.
const SERVICE_PASSWORD_ENV: &str = "SUPERX_KERNEL_PASSWORD";

/// The atomic kernel.
///
/// `Clone` because SurrealDB's `Surreal<Any>` is itself a cheap
/// `Arc`-internal type — clones share the same underlying connection.
/// This lets background tokio tasks (the capture engine, module
/// startups) each hold their own clone without lifetime gymnastics.
#[derive(Clone)]
pub struct Kernel {
    db: Surreal<Any>,
    /// The connection URL this kernel signed in over; `None` for
    /// [`Kernel::from_db`] constructions (tests hand the kernel an
    /// already-connected handle). Recorded so boot telemetry can
    /// state where the substrate lives.
    endpoint: Option<String>,
}

impl Kernel {
    /// Connect to an operator-provisioned SurrealDB and sign in as
    /// the `superx_kernel` service account.
    ///
    /// Pure connect + signin — **no telemetry is emitted**. Read-only
    /// commands connect through here too, and readers must not mutate
    /// the stream they observe; boot telemetry belongs to the boot
    /// orchestrator (G3).
    ///
    /// `endpoint` is a SurrealDB connection URL — `ws://host:port`,
    /// `http://host:port`, or `mem://` (test fixtures). `namespace`
    /// and `database` select the SuperX deployment within the engine.
    ///
    /// # Errors
    ///
    /// [`KernelError::Config`] if `SUPERX_KERNEL_PASSWORD` is not set.
    /// [`KernelError::Db`] if the engine refuses the connection, the
    /// namespace/database selection, or the signin — e.g. when the
    /// schema has not been deployed yet or the password does not match
    /// the one bound at schema-deploy time.
    pub async fn connect_service(
        endpoint: &str,
        namespace: &str,
        database: &str,
    ) -> Result<Self> {
        let password = std::env::var(SERVICE_PASSWORD_ENV).map_err(|_| {
            KernelError::Config(format!(
                "{SERVICE_PASSWORD_ENV} is not set — export the same value \
                 used at schema-deploy time (scripts/deploy-schema.sh)"
            ))
        })?;
        Self::connect_service_with_password(endpoint, namespace, database, &password).await
    }

    /// [`Kernel::connect_service`] with the password supplied by the
    /// caller instead of the environment — the CLI resolves it from
    /// env or the instance credentials file written by
    /// `superx --initialize`.
    ///
    /// # Errors
    ///
    /// [`KernelError::Db`] as for [`Kernel::connect_service`].
    pub async fn connect_service_with_password(
        endpoint: &str,
        namespace: &str,
        database: &str,
        password: &str,
    ) -> Result<Self> {
        let password = password.to_string();
        let db = connect(endpoint).await?;
        db.use_ns(namespace).use_db(database).await?;
        if let Err(e) = db
            .signin(Database {
                namespace: namespace.to_string(),
                database: database.to_string(),
                username: SERVICE_USERNAME.to_string(),
                password,
            })
            .await
        {
            tracing::error!(endpoint, namespace, database, error = %e,
                "substrate signin refused for superx_kernel");
            return Err(e.into());
        }
        tracing::info!(endpoint, namespace, database,
            "substrate connected; signed in as superx_kernel");

        Ok(Self {
            db,
            endpoint: Some(endpoint.to_string()),
        })
    }

    /// Wrap an already-authenticated [`Surreal<Any>`] connection.
    ///
    /// Intended for integration tests that hand-construct the
    /// substrate (`mem://` engine, schema applied, signed in) and want
    /// to exercise the kernel verbs against it. Production code paths
    /// go through [`Kernel::connect_service`].
    #[must_use]
    pub fn from_db(db: Surreal<Any>) -> Self {
        Self { db, endpoint: None }
    }

    /// The connection URL this kernel signed in over, if known.
    #[must_use]
    pub fn endpoint(&self) -> Option<&str> {
        self.endpoint.as_deref()
    }

    /// Underlying SurrealDB handle. Read-only access for modules +
    /// tests that need to issue raw queries (e.g. test fixtures
    /// applying DDL).
    #[must_use]
    pub fn db(&self) -> &Surreal<Any> {
        &self.db
    }

    // ─────────────────────────────────────────────────────────────────
    // Substrate verbs — CREATE / SELECT only
    // ─────────────────────────────────────────────────────────────────

    /// Idempotently CREATE one `type_definition` row, returning the
    /// resolved [`RecordId`]. If a row with this `uid` already exists,
    /// returns its id without creating a new row.
    ///
    /// Race-safe: the schema's UNIQUE index on `type_definition.uid`
    /// means a concurrent double-create loses to an engine refusal, in
    /// which case this verb re-reads and returns the winner's row.
    /// Types are immutable once created (SUPERX_SCHEMA.md §3.1).
    ///
    /// # Errors
    ///
    /// [`KernelError::Db`] for engine errors (e.g. `memory_tier` or
    /// `category` outside the schema-enforced `INSIDE [...]` ASSERT).
    pub async fn ensure_type_definition(
        &self,
        uid: &str,
        category: &str,
        memory_tier: &str,
    ) -> Result<RecordId> {
        if let Some(existing) = self.find_type_opt(uid).await? {
            return Ok(existing);
        }
        let id = self.new_record_id("type_definition");
        let row = TypeDefinitionRow {
            uid: uid.to_string(),
            category: category.to_string(),
            is_acyclic: true,
            sch_json: None,
            memory_tier: memory_tier.to_string(),
            valid_from: Utc::now(),
        };
        let created: std::result::Result<Option<TypeDefinitionRow>, surrealdb::Error> =
            self.db.create(id.clone()).content(row).await;
        match created {
            Ok(_) => Ok(id),
            // A concurrent creator may have won the UNIQUE(uid) race
            // between our find and our create — if the row now exists,
            // return it; otherwise the refusal was real.
            Err(e) => match self.find_type_opt(uid).await? {
                Some(winner) => Ok(winner),
                None => Err(e.into()),
            },
        }
    }

    /// Look up the [`RecordId`] of the `type_definition` row whose
    /// `uid` matches the argument.
    ///
    /// # Errors
    ///
    /// [`KernelError::NotFound`] if no such row exists;
    /// [`KernelError::Db`] for engine errors.
    pub async fn find_type(&self, uid: &str) -> Result<RecordId> {
        self.find_type_opt(uid)
            .await?
            .ok_or_else(|| KernelError::NotFound(format!("type_definition with uid '{uid}'")))
    }

    /// Look up the [`RecordId`] of the `type_definition` row by uid;
    /// `Ok(None)` if absent.
    ///
    /// # Errors
    ///
    /// [`KernelError::Db`] for engine errors.
    pub async fn find_type_opt(&self, uid: &str) -> Result<Option<RecordId>> {
        #[derive(SurrealValue)]
        struct IdOnly {
            id: RecordId,
        }
        let rows: Vec<IdOnly> = self
            .db
            .query("SELECT id FROM type_definition WHERE uid = $uid LIMIT 1")
            .bind(("uid", uid.to_string()))
            .await?
            .take(0)?;
        Ok(rows.into_iter().next().map(|r| r.id))
    }

    /// CREATE one row in `entity` with an explicit UUIDv7 id and a
    /// typed FK to the named `type_definition` row.
    ///
    /// # Errors
    ///
    /// [`KernelError::NotFound`] if `type_uid` doesn't resolve;
    /// [`KernelError::Db`] for engine errors (e.g. the
    /// type_definition's category is not `'node'`).
    pub async fn create_entity(&self, type_uid: &str) -> Result<RecordId> {
        let type_id = self.find_type(type_uid).await?;
        let id = self.new_record_id("entity");
        let row = EntityRow {
            r#type: type_id,
            valid_from: Utc::now(),
        };
        let _: Option<EntityRow> = self.db.create(id.clone()).content(row).await?;
        Ok(id)
    }

    /// CREATE one row in `relation` with an explicit UUIDv7 id,
    /// linking two entities via a typed edge.
    ///
    /// # Errors
    ///
    /// [`KernelError::NotFound`] if `type_uid` doesn't resolve;
    /// [`KernelError::Db`] for engine errors (e.g. the
    /// type_definition's category is not `'edge'`).
    pub async fn create_relation(
        &self,
        in_id: RecordId,
        out_id: RecordId,
        type_uid: &str,
        is_acyclic: bool,
    ) -> Result<RecordId> {
        let type_id = self.find_type(type_uid).await?;
        let id = self.new_record_id("relation");
        let row = RelationRow {
            in_: in_id,
            out: out_id,
            r#type: type_id,
            is_acyclic,
            valid_from: Utc::now(),
        };
        let _: Option<RelationRow> = self.db.create(id.clone()).content(row).await?;
        Ok(id)
    }

    /// CREATE one row in `state_ledger` with an explicit UUIDv7 id,
    /// attaching a typed attribute value to an entity.
    ///
    /// The substrate is append-only: this verb does NOT update a prior
    /// row in place. Every call creates a fresh row chained by
    /// `(target, type)`; the "current" value is recovered by
    /// [`Kernel::current_state`] (latest `valid_from` wins). SCD-2
    /// made literal (SUPERX_SCHEMA.md §1).
    ///
    /// # Errors
    ///
    /// [`KernelError::NotFound`] if `type_uid` doesn't resolve;
    /// [`KernelError::Db`] for engine errors.
    pub async fn supersede_state(
        &self,
        target: RecordId,
        type_uid: &str,
        payload: Value,
    ) -> Result<RecordId> {
        let type_id = self.find_type(type_uid).await?;
        let id = self.new_record_id("state_ledger");
        let row = StateLedgerRow {
            target,
            r#type: type_id,
            payload,
            valid_from: Utc::now(),
        };
        let _: Option<StateLedgerRow> = self.db.create(id.clone()).content(row).await?;
        Ok(id)
    }

    /// Find an entity by the `name` key of its latest descriptor-style
    /// attribute. The substrate names entities through `state_ledger`
    /// payloads, not entity columns — this is the canonical
    /// found-by-name lookup used by the module registry
    /// (`attr_module_descriptor`) and agent/source/session discovery
    /// (`attr_agent_descriptor`, …).
    ///
    /// A candidate row matching the name is only accepted if the
    /// target's **current** descriptor still carries that name — a
    /// renamed entity's old name must not resolve forever (v1 defect,
    /// fixed by design here).
    ///
    /// # Errors
    ///
    /// [`KernelError::NotFound`] if either type uid doesn't resolve;
    /// [`KernelError::Db`] for engine errors.
    pub async fn find_entity_by_name(
        &self,
        entity_type_uid: &str,
        attr_type_uid: &str,
        name: &str,
    ) -> Result<Option<RecordId>> {
        let entity_type = self.find_type(entity_type_uid).await?;
        let attr_type = self.find_type(attr_type_uid).await?;

        #[derive(SurrealValue)]
        struct TargetRow {
            target: RecordId,
            valid_from: DateTime<Utc>,
        }
        let rows: Vec<TargetRow> = self
            .db
            .query(
                "SELECT target, valid_from FROM state_ledger \
                 WHERE type = $attr_type \
                   AND target.type = $entity_type \
                   AND payload.name = $name \
                 ORDER BY valid_from DESC LIMIT 1",
            )
            .bind(("attr_type", attr_type))
            .bind(("entity_type", entity_type))
            .bind(("name", name.to_string()))
            .await?
            .take(0)?;

        let Some(candidate) = rows.into_iter().next().map(|r| r.target) else {
            return Ok(None);
        };
        // Verify against the target's CURRENT descriptor: a stale name
        // (superseded by a rename) does not resolve.
        let current = self.current_state(candidate.clone(), attr_type_uid).await?;
        let still_named = matches!(
            current,
            Some(Value::Object(ref obj))
                if matches!(obj.get("name"), Some(Value::String(s)) if s == name)
        );
        Ok(still_named.then_some(candidate))
    }

    /// Enumerate every entity of a type together with the latest
    /// payload of its descriptor-style attribute. Entities with no
    /// descriptor row yet are omitted (they have no name to list).
    ///
    /// # Errors
    ///
    /// [`KernelError::NotFound`] if the entity type uid doesn't
    /// resolve; [`KernelError::Db`] for engine errors.
    pub async fn list_named_entities(
        &self,
        entity_type_uid: &str,
        attr_type_uid: &str,
    ) -> Result<Vec<NamedEntity>> {
        let entity_type = self.find_type(entity_type_uid).await?;

        #[derive(SurrealValue)]
        struct IdOnly {
            id: RecordId,
        }
        let entities: Vec<IdOnly> = self
            .db
            .query("SELECT id FROM entity WHERE type = $type")
            .bind(("type", entity_type))
            .await?
            .take(0)?;

        let mut out = Vec::with_capacity(entities.len());
        for e in entities {
            let Some(payload) = self.current_state(e.id.clone(), attr_type_uid).await? else {
                continue;
            };
            out.push(NamedEntity {
                entity_id: e.id,
                payload,
            });
        }
        Ok(out)
    }

    /// Recover the latest `state_ledger.payload` for a
    /// `(target, type_uid)` chain. Returns `None` if no row has been
    /// written yet for that pair.
    ///
    /// `valid_from` is in the projection because the engine requires
    /// every ORDER BY idiom to appear in the selection.
    ///
    /// # Errors
    ///
    /// [`KernelError::NotFound`] if `type_uid` doesn't resolve;
    /// [`KernelError::Db`] for engine errors.
    pub async fn current_state(
        &self,
        target: RecordId,
        type_uid: &str,
    ) -> Result<Option<Value>> {
        let type_id = self.find_type(type_uid).await?;

        #[derive(SurrealValue)]
        struct PayloadRow {
            payload: Value,
            valid_from: DateTime<Utc>,
        }

        let rows: Vec<PayloadRow> = self
            .db
            .query(
                "SELECT payload, valid_from FROM state_ledger \
                 WHERE target = $target AND type = $type \
                 ORDER BY valid_from DESC LIMIT 1",
            )
            .bind(("target", target))
            .bind(("type", type_id))
            .await?
            .take(0)?;

        Ok(rows.into_iter().next().map(|r| r.payload))
    }

    // ─────────────────────────────────────────────────────────────────
    // Internal helpers
    // ─────────────────────────────────────────────────────────────────

    /// Construct a substrate [`RecordId`] for the given table with an
    /// explicit UUIDv7 row id. Per SUPERX_SCHEMA.md §1 every row id is
    /// set by the kernel; the engine never auto-generates one.
    pub(crate) fn new_record_id(&self, table: &'static str) -> RecordId {
        RecordId::new(table, surrealdb::types::Uuid::from(Uuid::now_v7()))
    }
}

/// One row of [`Kernel::list_named_entities`]: an entity plus the
/// latest payload of its descriptor-style attribute.
#[derive(Debug, Clone)]
pub struct NamedEntity {
    /// The entity's substrate identity.
    pub entity_id: RecordId,
    /// The latest descriptor payload (e.g. `{name, locator, adapter}`).
    pub payload: Value,
}

// ─────────────────────────────────────────────────────────────────────
// Substrate row shapes (private — internal serialization)
// ─────────────────────────────────────────────────────────────────────

#[derive(Debug, SurrealValue)]
struct TypeDefinitionRow {
    uid: String,
    category: String,
    is_acyclic: bool,
    sch_json: Option<String>,
    memory_tier: String,
    valid_from: DateTime<Utc>,
}

#[derive(Debug, SurrealValue)]
struct EntityRow {
    #[surreal(rename = "type")]
    r#type: RecordId,
    valid_from: DateTime<Utc>,
}

#[derive(Debug, SurrealValue)]
struct RelationRow {
    #[surreal(rename = "in")]
    in_: RecordId,
    out: RecordId,
    #[surreal(rename = "type")]
    r#type: RecordId,
    is_acyclic: bool,
    valid_from: DateTime<Utc>,
}

#[derive(Debug, SurrealValue)]
struct StateLedgerRow {
    target: RecordId,
    #[surreal(rename = "type")]
    r#type: RecordId,
    payload: Value,
    valid_from: DateTime<Utc>,
}
