//! The Kernel struct + substrate verbs.
//!
//! `Kernel` owns one [`Surreal<Any>`] connection authenticated as the
//! `superx_kernel` EDITOR service account (SKILL.md §13). All
//! substrate access by any layer above (kernel modules, drivers,
//! apps) goes through these verbs. There is NO `update_*`, no
//! `delete_*`, no `upsert_*`, no `connect_root` — the append-only
//! invariant is enforced by what the API does NOT contain.
//!
//! Every row id is set explicitly by the kernel as a UUIDv7 — never
//! auto-generated by the engine. Per skill §11 (audit `[S11-1]`).

use chrono::{DateTime, Utc};
use surrealdb::engine::any::{connect, Any};
use surrealdb::opt::auth::Database;
use surrealdb::types::{RecordId, SurrealValue, Value};
use surrealdb::Surreal;
use uuid::Uuid;

use crate::error::{KernelError, Result};

/// Kernel service-account username — the kernel's only credential
/// after schema deploy. Locked by SKILL.md §13. Drivers and apps each
/// get their own service accounts when they ship.
const SERVICE_USERNAME: &str = "superx_kernel";

/// Env var the operator sets to provision the kernel service-account
/// password.
const SERVICE_PASSWORD_ENV: &str = "SUPERX_KERNEL_PASSWORD";

/// v0.1 dev default published in SKILL.md §13 + SUPERX_SCHEMA.md
/// "Database users + access". Operator overrides via the env var above.
/// Documented in the skill so the literal here is the skill, not magic.
const SERVICE_PASSWORD_DEV_DEFAULT: &str = "superx-kernel-v01-dev-x9KmP2nQ7tR3vW8y";

/// The atomic kernel.
///
/// `Clone` because SurrealDB's `Surreal<Any>` is itself a cheap
/// `Arc`-internal type — clones share the same underlying connection.
/// This lets background tokio tasks (the capture loop, the emission
/// subscriber, etc.) each hold their own clone without lifetime
/// gymnastics.
#[derive(Clone)]
pub struct Kernel {
    db: Surreal<Any>,
}

impl Kernel {
    /// Connect to an operator-provisioned SurrealDB and sign in as
    /// the `superx_kernel` service account. Emits one `system_boot`
    /// telemetry event on success.
    ///
    /// `endpoint` is a SurrealDB connection URL — `ws://host:port`,
    /// `wss://host:port`, `http://host:port`, `https://host:port`,
    /// or `mem://` (test fixtures). `namespace` and `database`
    /// select the SuperX deployment within the engine.
    ///
    /// The service-account password is read from the
    /// `SUPERX_KERNEL_PASSWORD` env var; if absent it falls back to
    /// the v0.1 dev default documented in SKILL.md §13.
    ///
    /// # Errors
    ///
    /// Returns [`KernelError::Db`] if the engine refuses the
    /// connection, the namespace/database selection, or the signin
    /// — e.g. when the schema has not been deployed yet or the
    /// password does not match the one bound at schema-deploy time.
    pub async fn connect_service(
        endpoint: &str,
        namespace: &str,
        database: &str,
    ) -> Result<Self> {
        let password = std::env::var(SERVICE_PASSWORD_ENV)
            .unwrap_or_else(|_| SERVICE_PASSWORD_DEV_DEFAULT.to_string());

        let db = connect(endpoint).await?;
        db.use_ns(namespace).use_db(database).await?;
        db.signin(Database {
            namespace: namespace.to_string(),
            database: database.to_string(),
            username: SERVICE_USERNAME.to_string(),
            password,
        })
        .await?;

        let kernel = Self { db };
        kernel.emit_system_boot(namespace, database, endpoint).await?;
        Ok(kernel)
    }

    /// Wrap an already-authenticated [`Surreal<Any>`] connection.
    ///
    /// Intended for integration tests that hand-construct the
    /// substrate (`mem://` engine, schema applied, signed in) and
    /// want to exercise the kernel verbs against it. Production
    /// code paths go through [`Kernel::connect_service`].
    #[must_use]
    pub fn from_db(db: Surreal<Any>) -> Self {
        Self { db }
    }

    /// Underlying SurrealDB handle. Read-only access for kernel
    /// modules + tests that need to issue raw queries (e.g. test
    /// fixtures applying DDL).
    #[must_use]
    pub fn db(&self) -> &Surreal<Any> {
        &self.db
    }

    // ─────────────────────────────────────────────────────────────────
    // Substrate verbs — CREATE / SELECT only
    // ─────────────────────────────────────────────────────────────────

    /// Idempotently CREATE one `type_definition` row, returning the
    /// resolved [`RecordId`]. If a row with this `uid` already
    /// exists, returns its id without creating a new row.
    ///
    /// This is the primitive every kernel module / driver / app
    /// calls in its startup to register the type_definitions it
    /// introduces. Idempotent — safe to call on every boot.
    ///
    /// # Errors
    ///
    /// [`KernelError::Db`] for engine errors (e.g. `memory_tier`
    /// outside the schema-enforced `INSIDE [...]` ASSERT).
    pub async fn ensure_type_definition(
        &self,
        uid: &str,
        category: &str,
        memory_tier: &str,
    ) -> Result<RecordId> {
        if let Some(existing) = self.find_type_opt(uid).await? {
            return Ok(existing);
        }
        let id = self.new_record_id("type_definition");
        let row = TypeDefinitionRow {
            uid: uid.to_string(),
            category: category.to_string(),
            is_acyclic: true,
            sch_json: None,
            memory_tier: memory_tier.to_string(),
            valid_from: Utc::now(),
        };
        let _: Option<TypeDefinitionRow> = self.db.create(id.clone()).content(row).await?;
        Ok(id)
    }

    /// Look up the [`RecordId`] of the `type_definition` row whose
    /// `uid` matches the argument. Returns [`KernelError::NotFound`]
    /// if no such row exists.
    pub async fn find_type(&self, uid: &str) -> Result<RecordId> {
        self.find_type_opt(uid)
            .await?
            .ok_or_else(|| KernelError::NotFound(format!("type_definition with uid '{uid}'")))
    }

    /// Look up the [`RecordId`] of the `type_definition` row by uid;
    /// `Ok(None)` if absent.
    pub async fn find_type_opt(&self, uid: &str) -> Result<Option<RecordId>> {
        #[derive(SurrealValue)]
        struct IdOnly {
            id: RecordId,
        }
        let rows: Vec<IdOnly> = self
            .db
            .query("SELECT id FROM type_definition WHERE uid = $uid LIMIT 1")
            .bind(("uid", uid.to_string()))
            .await?
            .take(0)?;
        Ok(rows.into_iter().next().map(|r| r.id))
    }

    /// CREATE one row in `entity` with an explicit UUIDv7 id (§11)
    /// and a typed FK to the named `type_definition` row.
    ///
    /// # Errors
    ///
    /// [`KernelError::NotFound`] if `type_uid` doesn't resolve;
    /// [`KernelError::Db`] for engine errors (e.g. role outside the
    /// engine-enforced `INSIDE ['user', 'admin']` ASSERT, or the
    /// type_definition's category is not `'node'`).
    pub async fn create_entity(&self, type_uid: &str, role: &str) -> Result<RecordId> {
        let type_id = self.find_type(type_uid).await?;
        let id = self.new_record_id("entity");
        let row = EntityRow {
            r#type: type_id,
            role: role.to_string(),
            valid_from: Utc::now(),
        };
        let _: Option<EntityRow> = self.db.create(id.clone()).content(row).await?;
        Ok(id)
    }

    /// CREATE one row in `relation` with an explicit UUIDv7 id (§11),
    /// linking two entities via a typed edge.
    ///
    /// # Errors
    ///
    /// [`KernelError::NotFound`] if `type_uid` doesn't resolve;
    /// [`KernelError::Db`] for engine errors (e.g. the
    /// type_definition's category is not `'edge'`).
    pub async fn create_relation(
        &self,
        in_id: RecordId,
        out_id: RecordId,
        type_uid: &str,
        is_acyclic: bool,
    ) -> Result<RecordId> {
        let type_id = self.find_type(type_uid).await?;
        let id = self.new_record_id("relation");
        let row = RelationRow {
            in_: in_id,
            out: out_id,
            r#type: type_id,
            is_acyclic,
            valid_from: Utc::now(),
        };
        let _: Option<RelationRow> = self.db.create(id.clone()).content(row).await?;
        Ok(id)
    }

    /// CREATE one row in `state_ledger` with an explicit UUIDv7 id
    /// (§11), attaching a typed attribute value to an entity.
    ///
    /// The substrate is append-only: this verb does NOT update a
    /// prior row in place. Every call creates a fresh row chained by
    /// `(target, type)`; the "current" value is recovered by
    /// [`Kernel::current_state`] (which selects the latest by
    /// `valid_from`). SCD-2 made literal.
    ///
    /// # Errors
    ///
    /// [`KernelError::NotFound`] if `type_uid` doesn't resolve;
    /// [`KernelError::Db`] for engine errors.
    pub async fn supersede_state(
        &self,
        target: RecordId,
        type_uid: &str,
        payload: Value,
    ) -> Result<RecordId> {
        let type_id = self.find_type(type_uid).await?;
        let id = self.new_record_id("state_ledger");
        let row = StateLedgerRow {
            target,
            r#type: type_id,
            payload,
            valid_from: Utc::now(),
        };
        let _: Option<StateLedgerRow> = self.db.create(id.clone()).content(row).await?;
        Ok(id)
    }

    /// Recover the latest `state_ledger.payload` for a
    /// `(target, type_uid)` chain. Returns `None` if no row has
    /// been written yet for that pair.
    ///
    /// # Errors
    ///
    /// [`KernelError::NotFound`] if `type_uid` doesn't resolve;
    /// [`KernelError::Db`] for engine errors.
    pub async fn current_state(
        &self,
        target: RecordId,
        type_uid: &str,
    ) -> Result<Option<Value>> {
        let type_id = self.find_type(type_uid).await?;

        #[derive(SurrealValue)]
        struct PayloadRow {
            payload: Value,
            valid_from: DateTime<Utc>,
        }

        let rows: Vec<PayloadRow> = self
            .db
            .query(
                "SELECT payload, valid_from FROM state_ledger \
                 WHERE target = $target AND type = $type \
                 ORDER BY valid_from DESC LIMIT 1",
            )
            .bind(("target", target))
            .bind(("type", type_id))
            .await?
            .take(0)?;

        Ok(rows.into_iter().next().map(|r| r.payload))
    }

    // ─────────────────────────────────────────────────────────────────
    // Internal helpers
    // ─────────────────────────────────────────────────────────────────

    /// Construct a substrate [`RecordId`] for the given table with an
    /// explicit UUIDv7 row id. Per SKILL.md §11 every row id is set
    /// by the kernel; the engine never auto-generates one.
    pub(crate) fn new_record_id(&self, table: &'static str) -> RecordId {
        RecordId::new(table, surrealdb::types::Uuid::from(Uuid::now_v7()))
    }

    /// Emit one `system_boot` telemetry event right after signin.
    /// Called from `connect_service` so the firehose lights up the
    /// moment the kernel is alive — observable to any subscriber
    /// before any kernel module has registered.
    async fn emit_system_boot(
        &self,
        namespace: &str,
        database: &str,
        endpoint: &str,
    ) -> Result<()> {
        let mut payload = surrealdb::types::Object::new();
        payload.insert("namespace".to_string(), Value::String(namespace.to_string()));
        payload.insert("database".to_string(), Value::String(database.to_string()));
        payload.insert("endpoint".to_string(), Value::String(endpoint.to_string()));
        payload.insert("service_account".to_string(), Value::String(SERVICE_USERNAME.to_string()));

        // Use log_telemetry from the telemetry module — same crate.
        crate::telemetry::log_telemetry_inner(
            &self.db,
            self.new_record_id("telemetry_stream"),
            "system_boot",
            Value::Object(payload),
            None,
        )
        .await
    }
}

// ─────────────────────────────────────────────────────────────────────
// Substrate row shapes (private — internal serialization)
// ─────────────────────────────────────────────────────────────────────

#[derive(Debug, SurrealValue)]
struct TypeDefinitionRow {
    uid: String,
    category: String,
    is_acyclic: bool,
    sch_json: Option<String>,
    memory_tier: String,
    valid_from: DateTime<Utc>,
}

#[derive(Debug, SurrealValue)]
struct EntityRow {
    #[surreal(rename = "type")]
    r#type: RecordId,
    role: String,
    valid_from: DateTime<Utc>,
}

#[derive(Debug, SurrealValue)]
struct RelationRow {
    #[surreal(rename = "in")]
    in_: RecordId,
    out: RecordId,
    #[surreal(rename = "type")]
    r#type: RecordId,
    is_acyclic: bool,
    valid_from: DateTime<Utc>,
}

#[derive(Debug, SurrealValue)]
struct StateLedgerRow {
    target: RecordId,
    #[surreal(rename = "type")]
    r#type: RecordId,
    payload: Value,
    valid_from: DateTime<Utc>,
}
